# generated by datamodel-codegen:
#   filename:  library.yaml

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class ModelFormat(StrEnum):
    """
    On-disk format of a model. A dimension of the data model rather
    than an assumption (locked 2026-09-08): both are implemented at
    v0.1, and the differences are load-bearing rather than
    cosmetic.

    * `gguf` — a single file, quantized, carrying its own metadata
      and tokenizer. Large models may be **split** into
      `…-00001-of-0000N.gguf` shards, of which only the first is
      named on a launch line. A multimodal GGUF ships its vision
      projector as a separate file in the same directory, which is
      not itself a model.
    * `safetensors` — a directory: `config.json` plus one or more
      weight files plus tokenizer files. Unquantized in practice,
      so **no quant tier** — a safetensors model is sized, not
      tiered, and the quant fields exist only on the GGUF side.

    Shared because it appears on both sides of a join: a library
    entry declares what a model *is*, and
    `EngineDescriptor.modelFormats` declares what an engine can
    *load*. Nothing can serve a safetensors model until the vLLM
    adapter lands, and that answer comes from the engine's
    descriptor rather than from anything the library knows.

    """

    gguf = 'gguf'
    safetensors = 'safetensors'


class Role(StrEnum):
    """
    The speaker of a single message in a conversation. Matches the
    OpenAI / Anthropic chat roles so adapters never re-shape on a hop.

    """

    system = 'system'
    user = 'user'
    assistant = 'assistant'


class Message(BaseModel):
    """
    A single message in a conversation. Deliberately close to the
    OpenAI / Anthropic chat message format so drivers don't have to
    re-shape on every hop.

    """

    role: Role
    content: str = Field(
        ...,
        description='Message text. Text-only for now; multimodal extensions deferred.',
    )
    timestamp: AwareDatetime | None = Field(
        None, description='When the message was produced. Server-assigned if omitted.'
    )


class BackendKind(StrEnum):
    """
    Which wire protocol an inference-driver instance speaks to its
    backend. Reported by the driver's `/v1/info` so the gateway can
    log it and the UI can render a label.

    `openai_compat_http` covers every local engine we care about
    (llama.cpp's `llama-server`, vLLM, LM Studio, Ollama) as well as
    hosted OpenAI-compatible services — the protocol is shared even
    though the providers are not, so `DriverInfo.provider` is what
    distinguishes them. `claude_code_cli` and `codex_cli` shell out
    to the respective CLIs, which is how a subscription the operator
    already pays for becomes just another backend.

    """

    anthropic_api = 'anthropic_api'
    openai_api = 'openai_api'
    claude_code_cli = 'claude_code_cli'
    codex_cli = 'codex_cli'
    openai_compat_http = 'openai_compat_http'


class ComponentKind(StrEnum):
    """
    Which Eugene Plexus component class a topology entry
    represents. Lives in `common.yaml` because more than one
    component references it: the watchdog's `/v1/components`, and
    (via `ConfigField.componentKindHint`) any component declaring
    a config field that points at a peer of a specific kind.

    A component is a **Eugene Plexus process**. Engine processes
    are not components and are not named here — they are runtimes,
    declared separately on the watchdog, because a third-party
    binary shares none of a component's declarative shape (no
    module, no config trio, no service token). See the watchdog's
    `GET /v1/runtimes`.

    `gateway` is the one OpenAI-compatible front door and there is
    exactly one. `inference-driver` instances are the per-backend
    wrappers and there are N — one per backend, wherever that
    backend lives. `library` scans the operator's model
    directories and holds per-model launch profiles; there is
    exactly one, and it is deliberately not in the request path.

    """

    gateway = 'gateway'
    inference_driver = 'inference-driver'
    library = 'library'


class EngineKind(StrEnum):
    """
    Which engine adapter constructs the argv and interprets
    readiness. Deliberately a closed enum rather than a free string:
    an engine is supported exactly when an adapter exists for it,
    and without an adapter there is nothing that knows how to start
    it or tell when it is ready.

    `llama_cpp` drives upstream `llama-server`. vLLM is a second
    adapter later, and MLX after that. We never ship an engine — all
    three are upstream projects we wrap and track.

    Lives here rather than on the watchdog because two components
    reference it: the watchdog's engines and runtimes, and a
    library `ModelProfile`, which names the engine its launch flags
    are written for.

    """

    llama_cpp = 'llama_cpp'


class Problem(BaseModel):
    """
    Error response shape, modeled on RFC 7807 (problem+json). Every
    Eugene Plexus component returns this for 4xx / 5xx responses.

    """

    type: str = Field(
        ...,
        description='A URI reference identifying the problem type, per RFC 7807.\nModeled as a plain string rather than `format: uri` to keep\nsentinel values like `about:blank` and ergonomic at call sites.\n',
    )
    title: str = Field(..., description='Short human-readable summary.')
    status: int = Field(..., description='HTTP status code.')
    detail: str | None = Field(
        None, description='Human-readable explanation specific to this occurrence.'
    )
    instance: str | None = Field(
        None,
        description='A URI reference identifying the specific occurrence. Modeled\nas a plain string for the same reason as `type`.\n',
    )
    component: str | None = Field(
        None,
        description='Eugene Plexus component name that originated the error\n(e.g. `"gateway"`, `"inference-driver:left"`).\n',
    )


class Status(StrEnum):
    ok = 'ok'
    degraded = 'degraded'
    error = 'error'


class Health(BaseModel):
    """
    Liveness / readiness response shape.
    """

    status: Status
    version: str | None = Field(None, description='Component version (semver).')
    component: str | None = Field(
        None, description='Component identifier (e.g. `"inference-driver"`).'
    )
    safeMode: bool | None = Field(
        False,
        description="True when the component was started with the watchdog's\nsafe-mode env var set\n(`EUGENE_PLEXUS_<KIND>_SAFE_MODE=1`) and is therefore\nrunning on built-in defaults instead of its persisted\nconfig. Components in safe mode are reachable for config\nediting (`PATCH /v1/config` writes to disk normally) but\nshould be considered non-functional for their primary\npurpose until restarted without the flag. `status` is\nalso reported as `degraded` while safe mode is in effect.\n",
    )
    details: dict[str, Any] | None = Field(
        None, description='Optional component-specific health detail.'
    )


class ConfigValueType(StrEnum):
    """
    The kind of value a config field holds. The UI uses this to pick
    a renderer (text input, dropdown, password field, etc.).

    Two of these hold more than a scalar. `path_list` is an ordered
    JSON array of directory paths on the component host — the
    library's model roots are the first and so far only user — and
    the UI renders it as an add/remove list of directory pickers
    rather than a text field, because asking someone to
    comma-separate Windows paths is asking for a bug report. Order
    is preserved and meaningful: it is the order the operator sees,
    and M3's downloader offers the first entry as the default
    destination. `driver_list` stays reserved for M5's ordered
    model→driver priority lists.

    """

    string = 'string'
    integer = 'integer'
    number = 'number'
    boolean = 'boolean'
    enum = 'enum'
    secret = 'secret'
    file_path = 'file_path'
    path_list = 'path_list'
    url = 'url'
    duration = 'duration'
    driver_list = 'driver_list'


class ConfigFieldShowWhen(BaseModel):
    """
    Predicate over another `ConfigField`'s current value. The UI
    renders the field this is attached to only when the named field
    equals the given value (or matches one entry in the given list).

    """

    key: str = Field(
        ...,
        description='`key` of another field in the same `ConfigSchema` to compare\nagainst.\n',
    )
    equals: Any = Field(
        ...,
        description="Value the named field must equal for this field to render.\nUntyped — when scalar, matches by literal equality against\nthe referenced field's `valueType`. When an array, matches\nif the referenced field's current value equals any entry\n(set-membership). Use the array form for a field that\napplies to multiple entries of an enum (e.g. an `apiKey`\nfield shared across several OpenAI-compatible providers).\n",
    )


class ConfigDocument(BaseModel):
    """
    Current effective config values, keyed by `ConfigField.key`.
    Values of fields with `sensitive: true` are returned as the
    literal string `"<redacted>"` regardless of whether they are
    set. Returned by `GET /v1/config`.

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigUpdateRequest(BaseModel):
    """
    Partial update for `PATCH /v1/config`. Every present key is
    set; absent keys are left unchanged. To revert a field to its
    default, send `null` as the value. Sensitive fields are written
    through directly (the redacted form sent back by GET is never
    accepted as a write value).

    """

    model_config = ConfigDict(
        extra='allow',
    )


class ConfigFieldError(BaseModel):
    """
    A per-field validation failure during PATCH.
    """

    key: str
    message: str


class ConfigUpdateResult(BaseModel):
    """
    Outcome of a `PATCH /v1/config` call. Validation failures on
    individual keys do not abort the whole request — valid changes
    are applied, invalid ones are reported in `rejected`.

    """

    applied: list[str] = Field(
        ..., description='Keys that were validated and applied successfully.'
    )
    rejected: list[ConfigFieldError] = Field(
        ...,
        description='Keys whose new values failed validation. The current value\nis preserved.\n',
    )
    requiresRestart: bool = Field(
        ...,
        description='True if any key in `applied` has `requiresRestart: true`,\nmeaning a process restart is needed for the change to take\neffect. The UI should surface this to the user.\n',
    )
    pendingRestart: list[str] | None = Field(
        None,
        description='Keys whose new values are stored but not yet active. Subset\nof `applied`. Empty unless `requiresRestart` is true.\n',
    )


class ConfigTestRequest(BaseModel):
    """
    Optional override for `POST /v1/config/test`. Same shape as
    `ConfigUpdateRequest`: keys override the saved config for the
    duration of the test only. Useful for "Test Connection" UIs where
    the operator wants to verify a new API key, URL, or model
    identifier before committing it. Send an empty body (`{}`) to
    test the saved config as-is.

    """

    overrides: ConfigUpdateRequest | None = None


class ConfigTestResult(BaseModel):
    """
    Result of a `POST /v1/config/test` invocation. Components decide
    what "test" means for their own surface: an inference-driver runs
    a minimal `generate()` round-trip against its backend; the
    gateway probes every driver it can route to; the library checks
    that its configured model directories are readable.

    """

    ok: bool = Field(
        ..., description='True iff the test invocation succeeded end-to-end.'
    )
    component: str = Field(
        ...,
        description='Component identifier (matches `ConfigSchema.component`).\nEchoed for UI clarity when several /v1/config/test responses\nland in the same view.\n',
    )
    latencyMs: int = Field(
        ..., description='Wall-clock time the test took, in milliseconds.'
    )
    summary: str | None = Field(
        None,
        description='One-line human-readable result summary. Always set when\n`ok` is true; may be set on failure to add context beyond\n`error`.\n',
    )
    sampleOutput: str | None = Field(
        None,
        description="Brief sample of the data the test produced — e.g. assistant\ntext from an inference-driver `generate()` round-trip. May be\ntruncated to keep the response small. Omitted when there's\nnothing useful to show.\n",
    )
    error: str | None = Field(
        None,
        description='Human-readable error message. Set when `ok` is false. Should\nbe specific enough that the operator can act on it (e.g.\n`"openaiApiKey rejected: 401 Unauthorized"`).\n',
    )


class SecurityMode(StrEnum):
    """
    Operator's choice for how the watchdog handles its master key
    between restarts. Set during the wizard's security screen; can
    be changed later from the Config page.

    * `prompt_on_startup` — passphrase required at every watchdog
      start. Master key lives only in process memory. Best for
      shared environments, sensitive conversations, security-
      conscious operators. A power outage means Eugene stays
      offline until the operator re-enters the passphrase.
    * `os_keyring` — master key stored in the OS secret store
      (Windows Credential Manager / macOS Keychain / Linux Secret
      Service via the `keyring` Python lib). OS unlocks tied to
      user login; Eugene auto-recovers from restarts. Best for
      home / personal-use installs and anyone who wants minimum
      friction. Anyone with the OS account can also start Eugene.

    """

    prompt_on_startup = 'prompt_on_startup'
    os_keyring = 'os_keyring'


class AuthLoginRequest(BaseModel):
    """
    Login request body sent by the UI to `POST /v1/auth/login` on
    the watchdog. The passphrase is the same one the operator set
    in the wizard. The watchdog bcrypt-compares it; on match,
    issues a session token.

    """

    passphrase: str = Field(..., min_length=1)


class AuthLoginResponse(BaseModel):
    """
    Issued on successful login. The UI stores `sessionToken` as a
    Secure / HttpOnly / SameSite=Strict cookie or in memory; every
    subsequent proxy request includes it as
    `Authorization: Bearer <token>`.

    """

    sessionToken: str = Field(
        ...,
        description='Opaque bearer token. Signed and validated server-side; the\nUI should never inspect its contents. Lifetime is bounded\nby `expiresAt`.\n',
    )
    expiresAt: AwareDatetime
    operatorName: str | None = Field(
        None,
        description='The operator\'s display name from the constitution\n(typically "operator" or whatever the operator set).\nEchoed for UI welcome strings.\n',
    )


class Alg(StrEnum):
    """
    Encryption algorithm identifier.
    """

    secretbox_xsalsa20poly1305 = 'secretbox-xsalsa20poly1305'


class MasterKeyEnvelope(BaseModel):
    """
    Encrypted-at-rest envelope for sensitive config fields. The
    on-disk YAML for fields marked `sensitive: true` is stored as
    this envelope when v0.2 security is enabled; the component
    decrypts using the master key passed in by the watchdog at
    spawn time (env var `EUGENE_PLEXUS_<KIND>_MASTER_KEY`,
    base64-encoded).

    Algorithm: libsodium secretbox (XSalsa20-Poly1305). The nonce
    is generated per-encryption and stored alongside the
    ciphertext. The master key is 32 bytes derived from the
    operator's passphrase via Argon2id with parameters chosen at
    first-run time and persisted in the watchdog's state.

    Components MAY accept plaintext values in PATCH requests
    (current behavior); on persist, they encrypt to this envelope
    if the master key is available. GET requests continue to
    return `"<redacted>"` for sensitive fields regardless of
    envelope-vs-plaintext on disk.

    """

    alg: Alg = Field(..., description='Encryption algorithm identifier.')
    nonce: str = Field(
        ...,
        description='Base64-encoded 24-byte nonce. Generated per-encryption,\nnever reused with the same key.\n',
    )
    ciphertext: str = Field(..., description='Base64-encoded ciphertext + auth tag.')


class RestartResult(BaseModel):
    """
    Acknowledgement returned by `POST /v1/admin/restart`. The
    component schedules its own process exit shortly after returning
    this response (typically a few hundred ms — long enough for the
    HTTP response to flush). The component does NOT bring itself
    back up; a process supervisor (systemd, docker-compose, the
    deploy launcher, etc.) is expected to relaunch it. In v0.1
    personal-use deploys without a supervisor, the operator
    relaunches manually.

    """

    scheduled: bool = Field(
        ...,
        description='True if the component accepted the restart and an exit is\nqueued. Always true in v0.1 — the endpoint has no reason to\nrefuse — but typed as a boolean so future versions can gate\non (e.g.) an in-flight long-running operation.\n',
    )
    delayMs: int = Field(
        ...,
        description='How long the component intends to wait before calling exit,\nmeasured from the moment the response is sent. Lets clients\ntime their UI ("restarting in 0.5s…") and decide when to\nstart polling `/healthz` for the relaunched process.\n',
        ge=0,
    )
    message: str | None = Field(
        None,
        description='Optional human-readable note (e.g. "logs flushed, exiting\nnow"). UI may display this in the restart-progress dialog.\n',
    )


class ModelStatus(StrEnum):
    """
    * `present` — found on disk and readable.
    * `missing` — not found by the last scan, but profiles are
      saved against it, so the entry survives. **Moving a model
      produces this**, plus a new entry at the new path: nothing
      guesses that a file which vanished from one root and appeared
      in another is the same file, because a wrong guess silently
      applies one model's tuning to another. The profiles stay here
      to be copied across by hand.
    * `unreadable` — the files are there and something about them
      did not work. `error` says what.

    """

    present = 'present'
    missing = 'missing'
    unreadable = 'unreadable'


class ModelCapabilities(BaseModel):
    """
    What the model's own metadata says it can do. Distinct from the
    watchdog's `RuntimeCapabilities`, which is read back off a
    *running* engine: this is a property of the file, available
    before anything is launched, and it is what the launch flags
    have to be chosen from.

    """

    chat: bool | None = Field(
        None,
        description='Text generation — the default assumption for a causal model.\nFalse for an embedding model.\n',
    )
    embedding: bool | None = Field(
        None,
        description='The model is a dedicated embedding model (a pooling type in\nits metadata, or non-causal attention). Load-bearing rather\nthan informational: llama-server\'s own help says\n`--embedding` is "for use only with dedicated embedding\nmodels", and launching one of these as a chat model does not\nfail — it starts, serves, and returns nonsense.\n',
    )
    vision: bool | None = Field(
        None,
        description='A vision projector was found for this model, so it can take\nimages. See `GgufDetail.projectorPath`.\n',
    )
    chatTemplate: bool | None = Field(
        None,
        description='The file embeds its own chat template. When false, something\nhas to supply one at launch, and a model answering strangely\nwith no template is a common and confusing failure.\n',
    )


class ModelFileRole(StrEnum):
    """
    * `weights` — the file named on the launch line. Exactly one per
      model: the single `.gguf`, the first shard of a split one, or
      the primary safetensors file.
    * `shard` — the second through Nth part of a split model.
    * `projector` — a vision projector (`general.type: mmproj`),
      which is why it is a role here and not a model of its own.
    * `config` / `tokenizer` / `index` — safetensors sidecars.
    * `other` — present in the model's directory, counted in
      `sizeBytes`, not classified.

    """

    weights = 'weights'
    shard = 'shard'
    projector = 'projector'
    config = 'config'
    tokenizer = 'tokenizer'
    index = 'index'
    other = 'other'


class SafetensorsDetail(BaseModel):
    """
    Safetensors-specific metadata. Present iff `format` is
    `safetensors`. **No quant fields** — a safetensors model is
    sized, not tiered.

    """

    dtype: str | None = Field(
        None,
        description='Dominant tensor dtype as the header declares it, e.g.\n`"BF16"`, `"F16"`, `"F32"`. The nearest thing to a quant\ntier here, and it is a precision rather than a scheme.\n',
    )
    shardCount: int | None = Field(
        None,
        description='Number of `model-0000N-of-0000M.safetensors` files. Unlike\nGGUF, all of them are loaded together and none is "the"\nfile — the directory is the model.\n',
        ge=1,
    )
    repoId: str | None = Field(
        None,
        description='HuggingFace repo this came from, e.g.\n`"sentence-transformers/all-MiniLM-L6-v2"`, when the layout\nsays so (a `models--<org>--<name>` cache directory, or\n`config.json` naming it).\n',
    )
    revision: str | None = Field(
        None,
        description="Snapshot revision, when the model sits in a HuggingFace\ncache. Those caches hold **one directory per revision**, so\nwithout this two snapshots of one model are two\nindistinguishable entries. The revision named by the\ncache's own `refs/main` is the current one; the others are\nreported as skipped older revisions rather than as models.\n",
    )
    configPath: str | None = Field(
        None,
        description='Absolute path to `config.json`, the file that made this a model.',
    )


class RecommendedSampling(BaseModel):
    """
    Sampling parameters the model's author put in the file
    (`general.sampling.*` in GGUF). **Reported, never applied.**

    The locked rule is that the gateway owns every
    LLM-output-affecting parameter and no component substitutes a
    local default; that rule is unchanged. But the file having an
    opinion is real information, and dropping it means the operator
    has to go read the model card to find out. Whether anything can
    adopt these with one click is a gateway decision, not a library
    one.

    """

    temperature: float | None = None
    topK: int | None = None
    topP: float | None = None


class ModelProfileSpec(BaseModel):
    """
    Declarative half of a profile — the launch settings that worked
    for one model. Used for create and replace bodies.

    Every field name here is a `RuntimeSpec` field name, on purpose:
    composing a profile into a runtime declaration is a copy, not a
    translation, which is what lets the launch flow live in the
    caller and keep this component free of engine knowledge.

    """

    name: str = Field(
        ...,
        description='Operator-supplied label, unique per model — "long context",\n"cpu only", "gpu 1". Names rather than numbers because the\nreason a profile exists is the thing worth remembering about\nit.\n',
        min_length=1,
    )
    default: bool | None = Field(
        False,
        description='The profile offered first when launching this model.\nSetting it clears the flag on whichever profile held it; the\nfirst profile saved for a model gets it whether it asks or\nnot.\n',
    )
    engine: EngineKind = Field(
        ...,
        description='Which engine these flags are written for. Flags are not\nportable between engines, so a profile is only ever offered\nfor the engine it names — and a model whose format no\ninstalled engine can load has nowhere to use one at all. The\nengine side of that answer is\n`EngineDescriptor.modelFormats` on the watchdog.\n',
    )
    flags: dict[str, Any] | None = Field(
        None,
        description="Curated engine flags, keyed by the field names in the\nadapter's `flagSchema` — context size, GPU layers, batch\nsize, parallel slots. Copied onto `RuntimeSpec.flags`\nverbatim.\n\n**Stored, not validated.** The validator is the watchdog's\nadapter schema, at runtime-creation time. A profile is\nallowed to be wrong; the runtime that uses it is not, and\nthat is where an unknown key becomes a 400. Validating in\nboth places would mean two copies of engine knowledge and\none of them going stale.\n",
    )
    extraArgs: list[str] | None = Field(
        None,
        description='Verbatim extra arguments, for the long tail a curated\nsurface always misses. `--lora` lives here, which is why\nadapters are not modelled as their own thing yet.\n',
    )
    env: dict[str, str] | None = Field(
        None,
        description='Extra environment for the engine process. This is where\n`CUDA_VISIBLE_DEVICES` goes, and therefore where the\ntwo-replicas-on-two-GPUs case comes from: the same profile\ntwice with a different device pinned. It is also the\nstrongest argument for profiles being plural.\n',
    )
    notes: str | None = Field(
        None,
        description='Free text from the operator. Tuning a model is empirical and\nthe reasoning evaporates — "OOMs above 24 layers on the\n3090" is worth more later than the flag value it explains.\n',
    )


class ModelProfile(BaseModel):
    """
    A saved profile, as stored: the spec plus server-owned
    identifiers and timestamps.

    """

    id: str = Field(
        ..., description='Server-assigned profile id, unique within the model.'
    )
    name: str
    default: bool
    engine: EngineKind
    flags: dict[str, Any] | None = None
    extraArgs: list[str] | None = None
    env: dict[str, str] | None = None
    notes: str | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class ScanRequest(BaseModel):
    full: bool | None = Field(
        False,
        description='Re-read metadata for every model instead of trusting the\n`(path, size, mtime)` cache. Costs the full walk — tens of\nmilliseconds per model, more cold — and exists for when the\nmetadata reader has changed rather than the files.\n',
    )


class ScanState(StrEnum):
    """
    * `idle` — nothing has been scanned yet this install.
    * `scanning` — in flight; poll for progress.
    * `done` — completed. Individual roots may still have failed;
      check `roots`.
    * `failed` — the scan itself could not run, e.g. no roots are
      configured at all.
    * `cancelled` — stopped by `DELETE /v1/scan`. Whatever it found
      is kept and reported, but the list is not complete and this
      state is what says so.

    """

    idle = 'idle'
    scanning = 'scanning'
    done = 'done'
    failed = 'failed'
    cancelled = 'cancelled'


class Status1(StrEnum):
    """
    `missing` and `unreadable` are separate on purpose: a path
    that does not exist is usually a typo or an unplugged drive,
    and one that exists but cannot be read is a permission
    problem. They need different advice. `pending` means the
    walk has not reached this root yet.

    """

    ok = 'ok'
    missing = 'missing'
    unreadable = 'unreadable'
    pending = 'pending'


class ScanRoot(BaseModel):
    """
    One configured root and how the walk went in it.
    """

    path: str
    status: Status1 = Field(
        ...,
        description='`missing` and `unreadable` are separate on purpose: a path\nthat does not exist is usually a typo or an unplugged drive,\nand one that exists but cannot be read is a permission\nproblem. They need different advice. `pending` means the\nwalk has not reached this root yet.\n',
    )
    modelsFound: int | None = Field(None, ge=0)
    filesScanned: int | None = Field(None, ge=0)
    error: str | None = None


class SkipReason(StrEnum):
    """
    Why a path is not an entry. Every value here is a real case
    found on a real disk, not a defensive placeholder:

    * `projector` — a vision projector (`general.type: mmproj`),
      which belongs to the model beside it. Nearly a gigabyte each
      on current models, so getting this wrong is visible.
    * `shard_member` — part 2..N of a split model, accounted for on
      the entry that owns part 1.
    * `adapter` — a LoRA or similar (`adapter_config.json` plus
      `adapter_model.safetensors`, and no base weights). Not
      modelled yet; `--lora` in `extraArgs` covers anyone who needs
      it now.
    * `older_revision` — a HuggingFace cache snapshot that is not
      the one `refs/main` names. Those caches keep one directory per
      revision, so without this a single model appears once per
      revision ever fetched.
    * `not_a_model` — infrastructure inside a HuggingFace cache
      (`blobs/`, `refs/`, and `.no_exist/`, which is a *negative*
      cache full of zero-byte files with real-looking names), or
      anything else structurally not a model.
    * `unreadable_header` — the file is there and the metadata would
      not parse. Reported rather than skipped silently.
    * `unsupported_format` — a model format with no scanner yet.
      MLX is the reserved case.
    * `incomplete_download` — a `.part` file from a download that
      is in flight, paused, or failed. No longer reserved: the
      downloader writes these into scanned roots by design, and a
      `paused` download is *expected* to leave one there. The
      matching `Download` record, if there is one, is what says
      whether it can be resumed; a `.part` with no record behind it
      is litter and can be deleted by hand.

    """

    projector = 'projector'
    shard_member = 'shard_member'
    adapter = 'adapter'
    older_revision = 'older_revision'
    not_a_model = 'not_a_model'
    unreadable_header = 'unreadable_header'
    unsupported_format = 'unsupported_format'
    incomplete_download = 'incomplete_download'


class CatalogueSort(StrEnum):
    """
    Ordering for a catalogue search. `trending` is upstream's own
    trending score, which is the closest thing to "what is worth
    looking at this week" — and, honestly, the ranking most likely
    to surface a keyword-stuffed finetune above an official release.
    The index is upstream's; we can filter and describe better than
    their search page but we cannot fix what it ranks.

    """

    downloads = 'downloads'
    likes = 'likes'
    trending = 'trending'
    modified = 'modified'
    created = 'created'


class GateKind(StrEnum):
    """
    Whether upstream restricts the *bytes*. `open` is unrestricted;
    `auto` needs a token and one click-through on the model page;
    `manual` needs a human approval that can take days.

    A three-valued enum rather than upstream's own
    `false | "auto" | "manual"`, which would be a boolean-or-string
    union in every generated client for no gain. `open` is the
    normalization of `false`.

    The three cases are distinguished because a gated repo browses
    perfectly — metadata, file list, sizes and digests are all
    public — and **only the download 401s.** Warning about it on
    the detail screen is the difference between a legible
    prerequisite and a mysterious failure after the operator has
    chosen a quant and pressed the button.

    """

    open = 'open'
    auto = 'auto'
    manual = 'manual'


class QuantSource(StrEnum):
    """
    **Where the tier came from, and this field is load-bearing.**
    `filename` at listing time, because the hub exposes no
    per-file quant and the name is all there is — the very thing
    a local scan refuses to trust. `metadata` after a preflight
    has read `general.file_type` over HTTP Range.

    Fit is computed from `sizeBytes`, which is authoritative
    either way, so a mislabelled file changes what is displayed
    and never what is promised.

    """

    filename = 'filename'
    metadata = 'metadata'


class CatalogueFile(BaseModel):
    """
    One file in an upstream repo, with whatever it can be verified against.
    """

    path: str = Field(
        ...,
        description='Repo-relative path, which is **not** a filename: split\nquants live in subdirectories (`BF16/…-00001-of-00002.gguf`).\nThe download writes the basename.\n',
    )
    sizeBytes: int = Field(..., ge=0)
    sha256: str | None = Field(
        None,
        description='Content digest, for the large files — every weight file is\nLFS-backed and carries one. Note that the entry also has a\n40-hex `oid` beside it upstream which is the sha1 of the\n136-byte LFS *pointer*, not of the model: verifying against\nthat passes on any download at all. This field is the real\none.\n',
    )
    gitBlobSha1: str | None = Field(
        None,
        description='For the small non-LFS files — `config.json`, the tokenizer\nfiles, the safetensors index — which have no content digest\nupstream. They are still verifiable:\n`sha1("blob <len>\\0" + bytes)`, checked exactly against a\nreal repo. Between this and `sha256` every file has\nsomething to check, so nothing is written unverified.\n',
    )
    role: ModelFileRole | None = None
    lfs: bool | None = Field(
        None,
        description='Whether upstream stores this through LFS. Decides which\ndigest is present, and also which redirect shape the\ndownload meets — a 302 to a signed CDN URL for LFS, a 307\nto an internal path for the rest, both mandatory to follow.\n',
    )


class CatalogueRecommendation(BaseModel):
    """
    Which candidate to take, and why. **The largest one that fully
    fits at the requested context** — not the largest that runs at
    all, because partial offload is a decision the operator should
    make knowingly rather than inherit from a recommendation.

    """

    label: str = Field(..., description="The recommended candidate's `label`.")
    reason: str = Field(
        ...,
        description='Prose, naming the numbers: what fits, at what context,\nagainst how much free memory. Differentiator #6 is "show\n*why*"; a bare recommendation with no arithmetic is the\nthing the source complaint is complaining about.\n',
    )
    lowQualityWarning: str | None = Field(
        None,
        description='Present when the largest thing that fits is below ~4 bits\nper weight, naming the alternatives — shorter context,\npartial offload, a smaller model. Recommending a 1.81-bpw\nquant without comment is how a first impression becomes\n"this thing is stupid", and the failure is ours rather than\nthe model\'s.\n',
    )


class MatchedOn(StrEnum):
    """
    `digest` is certain — the local file's hash was known and
    matched. `name_and_size` is a strong guess and labelled as
    one, because the library deliberately never hashes model
    content (a 40 GB read per scan is not on the table), so for
    most entries name and size is all there is to compare.

    """

    digest = 'digest'
    name_and_size = 'name_and_size'


class AlreadyOwned(BaseModel):
    """
    This candidate is already on the disk. The join only this
    component can make, since it holds both the catalogue and the
    library — and it is what stops a 16 GB re-download of a file the
    operator already has.

    """

    modelId: str = Field(..., description='The local `LibraryModel.id`.')
    path: str = Field(..., description='Where it already is.')
    matchedOn: MatchedOn | None = Field(
        None,
        description="`digest` is certain — the local file's hash was known and\nmatched. `name_and_size` is a strong guess and labelled as\none, because the library deliberately never hashes model\ncontent (a 40 GB read per scan is not on the table), so for\nmost entries name and size is all there is to compare.\n",
    )


class CatalogueCard(BaseModel):
    """
    The model card, as published.
    """

    repo: str
    revision: str | None = None
    markdown: str = Field(
        ...,
        description='The README verbatim. **Untrusted content** — written by\nwhoever uploaded the model — so a renderer must not execute\nanything in it and should not follow its links blindly.\n',
    )
    frontMatter: dict[str, Any] | None = Field(
        None,
        description="The card's YAML front matter as upstream parsed it: license,\nbase model, tags. Structured, so a UI can show the license\nwithout regexing prose.\n",
    )
    fetchedAt: AwareDatetime | None = None


class DownloadSpec(BaseModel):
    """
    What to fetch and where to put it. The file list is explicit
    rather than inferred from the repo: "download the model" has to
    mean something exact by the time it reaches the transfer loop,
    and the catalogue detail response has already grouped the repo
    into candidates whose `files` can be passed straight through.

    """

    repo: str = Field(..., description='Upstream repo id.')
    revision: str | None = Field(
        'main',
        description='Resolved to a commit at start and pinned for the life of\nthe download, so a resume days later fetches the same bytes\nit began with.\n',
    )
    files: list[str] = Field(
        ...,
        description='Repo-relative paths. Every shard of a split candidate, the\nprojector if the operator wants vision, and for safetensors\nthe sidecars as well as the weights. Take these from\n`CatalogueCandidate.files` and `CatalogueModel.projectors`.\n',
        min_length=1,
    )
    root: str | None = Field(
        None,
        description='Which configured model root to write under. Must be one of\nthem — this component will not write outside the\ndirectories the operator nominated. Defaults to the first,\nwhich is what the `path_list` config type has promised\nsince M2.\n',
    )
    subdirectory: str | None = Field(
        None,
        description='Relative destination under `root`, overriding the configured\nlayout. Path traversal is rejected; the result must stay\ninside the root.\n',
    )
    filename: str | None = Field(
        None,
        description='Override the written name of the **single-file** case. Rarely\nwanted: the upstream name is what the operator recognises,\nwhat the library will call it, and what\n`Runtime.modelAlias` defaults to — plainly-named files are\nthe point. Rejected when `files` holds more than one entry,\nbecause renaming one shard of a set breaks the set.\n',
    )


class DownloadState(StrEnum):
    """
    Named phases rather than a percentage, following M1's engine
    install for the same reason: the phases fail differently and the
    operator needs to know which one they are in. A stall in
    `downloading` is the network, a stall in `verifying` is the
    disk, and `verifying` *failing* is the one that means the bytes
    are wrong.

    * `queued` — accepted, waiting on `maxConcurrentDownloads`.
    * `resolving` — asking upstream for the commit, sizes and
      digests. Where a gated repo's 401 surfaces.
    * `paused` — operator-stopped; the `.part` is kept and shows up
      in the next scan as `incomplete_download`.
    * `cancelled` — operator-abandoned; the `.part` is removed.
    * `failed` — the retry budget is spent. `resume` runs the same
      loop again.

    """

    queued = 'queued'
    resolving = 'resolving'
    downloading = 'downloading'
    verifying = 'verifying'
    done = 'done'
    failed = 'failed'
    paused = 'paused'
    cancelled = 'cancelled'


class Basis(StrEnum):
    """
    `metadata` when the model's own declared shape produced the
    KV term — a local model, or a remote one after a preflight.
    `estimate` when only the file size was available, which is
    every catalogue candidate until someone preflights it.

    The honest distinction between "this is arithmetic" and
    "this is a guess with a number on it", and the field a UI
    should hang a "check this file" affordance off.

    """

    metadata = 'metadata'
    estimate = 'estimate'


class FitVerdict(StrEnum):
    """
    * `fits` — inside **free** VRAM. Fully offloaded, no host memory
      in the generation path.
    * `tight` — inside total VRAM but not free VRAM. It would fit on
      an idle GPU; something is holding memory right now, and
      closing it is the operator's call.
    * `split` — needs host memory as well. Runnable with partial
      offload, materially slower, and a decision rather than a
      failure.
    * `no` — larger than VRAM and RAM together.

    Four values rather than a percentage because a percentage of
    *what* — VRAM, or VRAM plus RAM? — is precisely the ambiguity
    the operator is trying to resolve, and because the four have
    different advice. `tight` and `split` are the two the field
    usually collapses into "won't fit", and they are the two worth
    naming.

    """

    fits = 'fits'
    tight = 'tight'
    split = 'split'
    no = 'no'


class Source(StrEnum):
    """
    `override` when the caller supplied the budget. That is how
    a model gets scored against **another** host's memory, which
    is the only honest answer in a deployment where the GPU is
    in a different building — and a UI should say which machine
    a verdict is about.

    """

    detected = 'detected'
    override = 'override'


class MemoryBudget(BaseModel):
    """
    What a fit verdict was measured against. **Free and total both,
    and free is what decides the verdict.** Measured on the dev box
    with nothing unusual running: 2.9 GiB of a 32 GiB card was
    already held and a third of RAM was in use — so scoring against
    total would have promised a fit that OOMs, and hiding total
    would have concealed what quitting a browser buys back.

    """

    vramFreeBytes: int | None = Field(None, ge=0)
    vramTotalBytes: int | None = Field(None, ge=0)
    largestGpuFreeBytes: int | None = Field(
        None,
        description='The biggest single card\'s free memory. Separate from the sum\nbecause llama.cpp splits layers across GPUs by default, so\n"fits on one card" and "fits across all of them" are\ndifferent questions with different performance — and two\nreplicas on two cards, which is M5\'s case, needs the\nper-card number rather than the total.\n',
        ge=0,
    )
    ramAvailableBytes: int | None = Field(None, ge=0)
    ramTotalBytes: int | None = Field(None, ge=0)
    gpuCount: int | None = Field(None, ge=0)
    unifiedMemory: bool | None = Field(
        None,
        description='Apple silicon, where the VRAM/RAM split does not exist and\nthe real ceiling is the wired limit rather than a separate\npool. Reported because the naive reading of "VRAM" on a\n96 GB Mac is zero, which would tell one of the better\nlocal-inference boxes on the market that it has no GPU.\n',
    )
    source: Source | None = Field(
        None,
        description="`override` when the caller supplied the budget. That is how\na model gets scored against **another** host's memory, which\nis the only honest answer in a deployment where the GPU is\nin a different building — and a UI should say which machine\na verdict is about.\n",
    )


class KvCacheType(StrEnum):
    """
    Element type assumed for the KV cache, which halves or quarters
    the cache term. `f16` is the default and llama.cpp's own.

    Present as a parameter because it is a launch flag
    (`--cache-type-k`) and therefore part of the question: "does
    this fit" has no answer that is independent of how it will be
    launched. A profile that sets the flag and a fit query that
    assumed `f16` disagree, and the operator should be able to see
    both.

    """

    f16 = 'f16'
    q8_0 = 'q8_0'
    q4_0 = 'q4_0'


class Os(StrEnum):
    windows = 'windows'
    linux = 'linux'
    macos = 'macos'


class Arch(StrEnum):
    x64 = 'x64'
    arm64 = 'arm64'


class Vendor(StrEnum):
    nvidia = 'nvidia'
    amd = 'amd'
    intel = 'intel'
    apple = 'apple'
    unknown = 'unknown'


class Gpu(BaseModel):
    index: int = Field(
        ...,
        description="The device index, which is what goes in\n`CUDA_VISIBLE_DEVICES` in a profile's `env` — the mechanism\nbehind two replicas on two cards.\n",
        ge=0,
    )
    name: str
    vendor: Vendor | None = None
    vramTotalBytes: int = Field(..., ge=0)
    vramFreeBytes: int | None = Field(
        None,
        description='Absent when the platform will not say. On a fresh desktop\nthis is around 2.9 GiB below total before anything is\nlaunched, which is 11% of a 24 GB card.\n',
        ge=0,
    )
    computeCapability: str | None = None
    driverVersion: str | None = None


class QuantTier(BaseModel):
    tier: str = Field(
        ...,
        description='The label as it appears in filenames, e.g. `Q4_K_M`, `IQ3_XXS`.',
    )
    family: str | None = Field(
        None,
        description='`legacy` (`Q4_0`, `Q8_0`), `k_quant` (`Q4_K_M` — mixed\nprecision per tensor), `i_quant` (`IQ*` — importance-matrix\nquantized), `dynamic` (`UD-*` — per-tensor choices made by\nthe publisher), or `unquantized` (`F16`, `BF16`, `F32`).\n',
    )
    nominalBitsPerWeight: float | None = Field(
        None,
        description="The tier's nominal width. The *actual* figure for a specific\nfile is `CatalogueCandidate.bitsPerWeight`, computed from its\nreal size — mixed-precision schemes do not land on their\nnominal value.\n",
    )
    summary: str = Field(..., description='What this tier does, in one sentence.')
    guidance: str | None = Field(
        None,
        description='When it is a sensible choice. Describes the **shape** of the\nquality curve — noticeable degradation below roughly 4 bits\nper weight, severe below 3 — and never a per-model\njudgement. Which of `IQ2_S` and `Q2_K` is better for a given\nmodel is upstream research and not ours to invent; a\nfabricated quality score is worse than none, the same rule\nthat makes an unrecognised `general.file_type` degrade to\nthe raw number.\n',
    )


class ConfigField(BaseModel):
    """
    UI-renderable description of a single editable config field.

    """

    key: str = Field(
        ...,
        description='Stable machine-readable id, dot-separated for grouping\n(e.g. `"adapter.modelId"`).\n',
    )
    label: str = Field(..., description='Human-readable label for the UI.')
    description: str | None = Field(
        None, description='One-sentence explanation suitable for non-programmers.'
    )
    category: str = Field(
        ...,
        description='Group key for UI tabbing or sectioning (e.g. `"adapter"`,\n`"logging"`, `"network"`). Mapped to a display label via\n`ConfigSchema.categories`.\n',
    )
    valueType: ConfigValueType
    default: Any | None = Field(
        None,
        description='Default value if unset. Type matches `valueType`. Omitted\nfor fields with no default.\n',
    )
    enumValues: list[str] | None = Field(
        None, description='Allowed values when `valueType == enum`.'
    )
    suggestions: list[str] | None = Field(
        None,
        description="Discovery-time hints — values the operator might want\nbut which AREN'T enforced by validation. UIs render\nstring-typed fields with non-empty `suggestions` as a\ncombobox (free-text input with a dropdown of suggestions)\nrather than a strict dropdown. Use when the set of\nvalid values is large, partially-discoverable, or\nextends beyond what the component knows at the moment\n(e.g. local LLM model lists that update when the operator\npulls a new model). Distinct from `enumValues`:\nsuggestions are advisory, enumValues are mandatory.\n",
    )
    componentKindHint: ComponentKind | None = Field(
        None,
        description="Declarative rendering hint: this field references a peer\ncomponent of the given kind. UIs render any kind-hinted\nfield as a dropdown sourced from the watchdog's\n`/v1/components` (filtered by kind), with `(off)` as the\nfirst option (saves an empty string). For single-instance\nkinds (memory, identity, etc.) the dropdown UX collapses\nto effectively a toggle; for multi-instance kinds\n(inference-driver) the operator picks one. Pairs with a\nstring/url `valueType` — the saved value is still the\npeer's URL, the hint only changes how the UI looks it up.\nAvoids the OpenClaw trap of duplicating topology into\nfree-text URL fields the operator has to type by hand.\n",
    )
    enumLabels: list[str] | None = Field(
        None,
        description='Optional human-readable display labels paired one-to-one\nwith `enumValues`. UIs that render an enum as a dropdown\nshould show `enumLabels[i]` while still submitting\n`enumValues[i]` as the saved value. When omitted (or\nshorter than `enumValues`), UIs fall back to the raw\nvalue as the label. Useful where the stored key is\nmachine-friendly but the user-facing label isn\'t —\ne.g. `claude_subscription` saved, "Claude (Pro/Max)"\nshown.\n',
    )
    sensitive: bool | None = Field(
        False,
        description='If true, the value is redacted (`"<redacted>"`) in\n`ConfigDocument` responses but is accepted in\n`ConfigUpdateRequest`. Use for API keys, passwords, etc.\n',
    )
    required: bool | None = Field(
        False,
        description='If true, the component will refuse to start without this\nfield set (either in config or via env var fallback).\n',
    )
    minimum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    maximum: float | None = Field(
        None, description='Validation hint for `integer` / `number` fields.'
    )
    pattern: str | None = Field(
        None, description='Regex validation hint for `string` / `url` / `file_path`.'
    )
    requiresRestart: bool | None = Field(
        False,
        description='If true, changes to this field via PATCH are accepted and\nstored but do not take effect until the component process\nrestarts. The UI should warn before submitting.\n',
    )
    showWhen: ConfigFieldShowWhen | None = Field(
        None,
        description="Conditional-rendering hint. When set, the UI should only\nrender this field when another field's current value matches\nthe condition. Used to hide adapter-specific fields\n(e.g. `openaiApiKey`) when a different adapter is selected.\nThe component still validates and stores the field\nregardless of UI visibility.\n",
    )


class ConfigSchema(BaseModel):
    """
    UI-renderable description of every editable config field this
    component accepts. Returned by `GET /v1/config/schema`. UIs use
    this to render a generic config editor without component-specific
    code.

    """

    component: str = Field(
        ..., description='Component identifier (e.g. `"inference-driver"`).'
    )
    fields: list[ConfigField]
    categories: dict[str, str] | None = Field(
        None,
        description='Map from category key (used in `ConfigField.category`) to\na human-readable section label. Optional; UIs may fall back\nto the raw key.\n',
    )


class ModelFile(BaseModel):
    """
    One file belonging to a model, and what part it plays.
    """

    path: str = Field(..., description='Absolute path.')
    role: ModelFileRole
    sizeBytes: int | None = Field(None, ge=0)


class GgufDetail(BaseModel):
    """
    GGUF-specific metadata, read from the file's KV block. Present
    iff `format` is `gguf`.

    """

    quantization: str | None = Field(
        None,
        description='Human-readable quant tier, e.g. `"Q4_K_M"`. The vocabulary\nthe operator\'s question is actually phrased in — "Q3_K_S vs\n2Q_K_M? No one knows" — and M3\'s guidance hangs off it.\n',
    )
    fileType: int | None = Field(
        None,
        description='Raw `general.file_type` enum value, reported alongside the\nlabel rather than instead of it. It **does** distinguish the\nK-quant mixtures (verified: 14 is `Q4_K_S`, 15 is `Q4_K_M`),\nso the label is machine-read rather than guessed from a\nfilename.\n\nReported raw because the quant families churn — imatrix\nvariants, MXFP4, whatever is next — and a reader will meet\nvalues it does not know. The rule for those is to surface\nthe number and the filename-derived label, never to map an\nunrecognised value onto a plausible neighbour: guidance\nbuilt on a guess is worse than no guidance.\n',
    )
    quantizationDisagrees: bool | None = Field(
        None,
        description='True when the label derived from `fileType` and the label in\nthe filename are not the same. Both are then reported and\nneither is silently preferred, because either one can be the\nwrong one — a requantized file keeps its old name more often\nthan a metadata field is wrong, but not always.\n',
    )
    ggufVersion: int | None = Field(
        None, description='GGUF container version (3 for everything current).'
    )
    shardCount: int | None = Field(
        None,
        description='Number of `…-0000N-of-0000M.gguf` parts. 1 for a plain file.\nOnly the first is on the launch line; the rest are `shard`\nfiles.\n',
        ge=1,
    )
    vocabSize: int | None = Field(
        None,
        description='Token count. Worth reporting for its own sake and because it\nexplains the scan cost: the tokenizer lives in the KV block,\nso a 248k-token vocab means ~10.9 MB of metadata to walk\npast before the quant can be read.\n',
        ge=0,
    )
    projectorPath: str | None = Field(
        None,
        description='Absolute path to the vision projector found beside this\nmodel, if any. Becomes `--mmproj` on the launch line.\nllama-server can also find it unaided, but it is reported\nbecause "this model can see" is a fact the browser should\nshow and a profile should be able to override.\n',
    )
    recommendedSampling: RecommendedSampling | None = None
    metadata: dict[str, Any] | None = Field(
        None,
        description='Selected raw KV pairs, verbatim, minus the tokenizer arrays.\nAn escape hatch for the long tail — architecture-prefixed\nkeys grow with upstream, and a reader that only ever exposes\nthe fields it was written to understand goes blind on every\nmodel newer than itself.\n',
    )


class ModelProfileList(BaseModel):
    profiles: list[ModelProfile]


class SkippedPath(BaseModel):
    """
    A path the scan saw and deliberately did not make a model of.
    """

    path: str
    reason: SkipReason
    detail: str | None = Field(
        None,
        description='Specifics — which model a projector belongs to, which entry\na shard is part of, what the header parser objected to.\n',
    )


class CatalogueSearchResult(BaseModel):
    """
    One upstream repository. **No sizes and no fit verdict** — see
    `searchCatalogue`: upstream's search response carries neither
    and synthesizing them would cost a call per row.

    """

    repo: str = Field(..., description='Full repo id, e.g. `unsloth/Qwen3.8-27B-GGUF`.')
    owner: str | None = Field(
        None,
        description='The publisher. Prominent on purpose — "which quant publisher\ndo I trust" is how people navigate this catalogue, and it is\nthe fastest signal that separates an official release from a\nreupload.\n',
    )
    name: str | None = None
    formats: list[ModelFormat] | None = Field(
        None,
        description='What this repo appears to serve, from its tags and library\nmetadata. Approximate at search time — a repo can hold both\nformats, and only the detail call reads the file list.\n',
    )
    gated: GateKind | None = None
    private: bool | None = None
    downloads: int | None = Field(None, ge=0)
    likes: int | None = Field(None, ge=0)
    trendingScore: float | None = None
    pipelineTag: str | None = Field(
        None, description="Upstream's task label, e.g. `text-generation`."
    )
    libraryName: str | None = None
    license: str | None = None
    tags: list[str] | None = None
    createdAt: AwareDatetime | None = None
    lastModified: AwareDatetime | None = Field(
        None,
        description='Worth showing next to popularity: a repo with millions of\ndownloads and no change in a year is a different\nproposition from one updated last week.\n',
    )


class DownloadFile(BaseModel):
    path: str = Field(..., description='Repo-relative source path.')
    destinationPath: str = Field(
        ...,
        description='Absolute path this file will occupy when it is done. While\nit is in flight the bytes live at this path plus `.part`.\n',
    )
    sizeBytes: int | None = Field(None, ge=0)
    bytesDownloaded: int | None = Field(None, ge=0)
    state: DownloadState
    sha256: str | None = Field(
        None, description='Expected content digest, when upstream published one.'
    )
    verified: bool | None = Field(
        None,
        description='Whether the finished file matched its digest. Verification\nhappens **before** the `.part` is renamed into place, so a\nfile that exists at `destinationPath` was verified — and one\nthat failed stays a `.part` with the record in `failed`,\nnever silently retried into the same bytes.\n',
    )
    role: ModelFileRole | None = None
    error: str | None = None


class Fit(BaseModel):
    """
    Whether a model runs on a given memory budget at a given
    context, **with the arithmetic attached**. One computation, three
    callers: per candidate in the catalogue, on a local model, and
    inside a preflight.

    It is an estimate and says so. The overhead allowance is flat,
    MoE models hold experts differently, and llama.cpp's own
    allocation shifts between builds — so the inputs are all
    reported, which is what makes a wrong answer diagnosable instead
    of merely wrong.

    """

    verdict: FitVerdict
    requiredBytes: int = Field(
        ..., description='`weightsBytes + kvCacheBytes + overheadBytes`.', ge=0
    )
    weightsBytes: int | None = Field(
        None,
        description='Summed over every file in the candidate, shards included.',
        ge=0,
    )
    kvCacheBytes: int | None = Field(
        None,
        description='`contextLength × attentionLayers × headCountKv ×\n(keyLength + valueLength) × bytes per element`. The term\nthat goes wrong: see `attentionLayers`.\n',
        ge=0,
    )
    overheadBytes: int | None = Field(
        None,
        description='Compute buffers, the graph, the accelerator context. A flat\nallowance, and the reason this is an estimate rather than a\ncalculation.\n',
        ge=0,
    )
    contextLength: int = Field(
        ...,
        description='The context this verdict is for. Change it and the verdict changes.',
        ge=1,
    )
    kvCacheType: KvCacheType | None = None
    attentionLayers: int | None = Field(
        None,
        description='Layers that actually hold a KV cache, which on a hybrid\nattention/SSM model is a small fraction of the total. Where\nthis is known from metadata the cache figure is real; where\nit is not, it is assumed equal to the layer count and\n`notes` says so — an assumption that is safe in the\npessimistic direction and, on one verified current model,\nwrong by 4.1×.\n',
        ge=0,
    )
    basis: Basis = Field(
        ...,
        description='`metadata` when the model\'s own declared shape produced the\nKV term — a local model, or a remote one after a preflight.\n`estimate` when only the file size was available, which is\nevery catalogue candidate until someone preflights it.\n\nThe honest distinction between "this is arithmetic" and\n"this is a guess with a number on it", and the field a UI\nshould hang a "check this file" affordance off.\n',
    )
    budget: MemoryBudget | None = None
    notes: list[str] | None = Field(
        None,
        description='The assumptions in words: full offload, F16 KV cache, layer\ncount assumed to be attention count, the overhead allowance\nused. Guidance that does not state its assumptions cannot be\nargued with, and this one will sometimes be wrong.\n',
    )


class ModelFit(BaseModel):
    """
    A local model's fit, plus which model it is about.
    """

    modelId: str
    path: str | None = None
    fit: Fit
    maxContextLength: int | None = Field(
        None,
        description="The largest context that still `fits` in free VRAM,\ncomputed by solving the same arithmetic for context instead\nof asserting it. More useful than a yes/no at one context:\nit is the number that goes in a profile's `-c`, and it\nanswers the question a launch actually asks.\n",
        ge=0,
    )
    modelContextLength: int | None = Field(
        None,
        description="What the model was trained for, for comparison. These two\nare frequently far apart — a current 27B declares 262144 and\nalmost nobody can hold that — and showing only the model's\nnumber is the comfortable lie M2 named.\n",
        ge=0,
    )


class HostHardware(BaseModel):
    """
    What this host has to spend, as detected. Deliberately **not**
    shared with the watchdog's `HostAccelerator`: that answers "which
    engine build do I fetch" and its own description already says the
    VRAM-and-fit surface belongs here. The two overlap on `os` and
    `arch` and diverge on everything else, so this duplicates two
    enums rather than coupling two surfaces that will evolve apart.
    When they disagree it is because they are on different hosts,
    which is information rather than a bug.

    """

    hostname: str = Field(
        ...,
        description='Which machine these numbers are from. Load-bearing in a\nmulti-host deployment: a driver lives next to its engine, so\nthe GPU that will load the model is not necessarily on the\nhost that measured this.\n',
    )
    os: Os
    arch: Arch
    cpuCount: int | None = Field(None, ge=1)
    ramTotalBytes: int | None = Field(None, ge=0)
    ramAvailableBytes: int | None = Field(
        None,
        description='What is actually free, which is a third less than total on\nan ordinary desktop. The number scoring uses.\n',
        ge=0,
    )
    unifiedMemory: bool | None = None
    gpus: list[Gpu] | None = None
    detectedAt: AwareDatetime | None = Field(
        None,
        description='Free memory moves constantly, so a verdict computed from a\ncached reading needs a timestamp on it.\n',
    )
    warnings: list[str] | None = Field(
        None,
        description='What could not be detected and what was assumed instead — no\nvendor tool on PATH, an accelerator whose free memory is\nunreadable, a platform whose memory model is not the one\nassumed. Named rather than silently defaulted: a fit verdict\ncomputed from a wrong budget is worse than no verdict, and\nthree of the detection paths in this component are\nunverified on real hardware (AMD, Intel, and Apple unified\nmemory).\n',
    )


class QuantTable(BaseModel):
    """
    Static reference content: what the quant tiers mean. Served from
    here so there is one copy to maintain as upstream's families
    churn, and so a headless install can print it.

    """

    tiers: list[QuantTier]
    updatedAt: AwareDatetime | None = Field(
        None, description='When this table was last revised, since the families move.'
    )


class LibraryModel(BaseModel):
    """
    One launchable model on this host.

    The format-independent facts are here; exactly one of `gguf` or
    `safetensors` carries the rest. That split is not tidiness — a
    quant tier is a GGUF concept and an exact parameter count is a
    safetensors one, and flattening both into one object would
    produce a schema half of whose fields are null for any given
    model.

    """

    id: str = Field(
        ...,
        description='Stable handle for this model: the first 16 hex characters of\nthe SHA-256 of its normalized absolute path. Normalized\nmeans absolute, canonical separators, case-folded on\nWindows, and **symlinks left unresolved**.\n\nDerived rather than random so it survives restarts, since\nprofiles are keyed to it. **Opaque to callers** — the\nnormalization rules are fiddly enough that a client deriving\nit independently would sooner or later compute a handle the\nserver does not recognise and get an unexplained 404. Use\n`GET /v1/models?path=` instead.\n\nNot content addressing: no byte of the model is read to\nproduce it. Hashing 40 GB on every scan is not on the table,\nand a content-derived identity would change when nothing the\noperator did changed.\n',
    )
    path: str = Field(
        ...,
        description="Absolute path, verbatim, in the operator's own layout — the\nmodel's real identity, reported in full because the `id` is\nnot human-readable and nothing here should be hidden behind\na handle.\n\nA `.gguf` file for GGUF (the **first** shard when split), a\ndirectory for safetensors. This is what goes on a runtime's\n`modelPath`.\n",
    )
    root: str | None = Field(
        None,
        description='The configured root this model was found under. Two roots\ncan hold the same filename, so this is how the UI\ndisambiguates two entries that otherwise read alike — and\nhow it tells the operator which drive to go plug back in.\n',
    )
    format: ModelFormat
    name: str = Field(
        ...,
        description="The filename with its extension stripped, or the directory\nname for safetensors. **Not derived from metadata**: the\nfile's own name is what the operator downloaded, what they\ncall it, and what `Runtime.modelAlias` defaults to — so\nplainly-named files mean the obvious name is already the\nright one.\n",
    )
    displayName: str | None = Field(
        None,
        description="The model's self-declared name from its metadata\n(`general.name` for GGUF), when it has one and it differs\nfrom `name`. Shown as a subtitle, never as the identity:\nmetadata names are frequently the training-run name and\ncollide across quants of one model.\n",
    )
    status: ModelStatus
    sizeBytes: int | None = Field(
        None,
        description='Total size of every file belonging to this model — all\nshards, and the projector when there is one. The number\nthat answers "will this fit on the drive I am copying it\nto", which is why it is a sum rather than the weights file\nalone.\n',
        ge=0,
    )
    fileCount: int | None = Field(
        None,
        description='How many files make up this model. 1 for a plain single-file GGUF.',
        ge=1,
    )
    architecture: str | None = Field(
        None,
        description='Model architecture as the file declares it — `general.architecture`\nfor GGUF, `model_type` from `config.json` for safetensors.\nFree-form on purpose: new architectures ship constantly and\nan enum here would reject models that work fine.\n',
    )
    contextLength: int | None = Field(
        None,
        description='Context length the **model** declares. Not what an engine\nwill serve — that depends on the launch flags and available\nmemory, and is reported by the watchdog as\n`RuntimeCapabilities.contextLength`. Both numbers are real\nand a UI that shows only this one tells a comfortable lie.\n',
        ge=0,
    )
    parameters: int | None = Field(
        None,
        description='Exact parameter count, when the format gives one. Safetensors\nheaders do (summed tensor shapes, from an ~11 KB read);\n**GGUF does not** — see `sizeLabel`. Optional because for\nmost local models it is genuinely unavailable, and a schema\nthat required it would be unfillable for every GGUF in\nexistence.\n',
        ge=0,
    )
    sizeLabel: str | None = Field(
        None,
        description='The author\'s own size label, e.g. `"27B"`\n(`general.size_label`). A display string, not a number, and\nnot always present or accurate — it is what the person who\nuploaded the file typed. For GGUF it is usually the only\nanswer available to "how big is this model".\n',
    )
    capabilities: ModelCapabilities | None = None
    files: list[ModelFile] | None = Field(
        None,
        description='Every file that belongs to this model, with its role. This\nis what makes a sharded model legible as one thing, and what\nshows the operator that the 900 MB projector next to their\nmodel is accounted for rather than missed.\n',
    )
    gguf: GgufDetail | None = None
    safetensors: SafetensorsDetail | None = None
    profileCount: int | None = Field(
        None,
        description='How many launch profiles are saved against this model. On\nthe list so the browser can badge a tuned model without\nfetching every profile collection.\n',
        ge=0,
    )
    firstSeenAt: AwareDatetime | None = Field(
        None, description='When a scan first found this model.'
    )
    lastSeenAt: AwareDatetime | None = Field(
        None,
        description='When a scan last found it on disk. For a `missing` entry\nthis is when it was last there, which is the only clue to\nwhat happened.\n',
    )
    modifiedAt: AwareDatetime | None = Field(
        None,
        description='Filesystem mtime of the weights. Part of the incremental-rescan key.',
    )
    error: str | None = Field(
        None,
        description='Why this entry is `unreadable` — a header that would not\nparse, a permission error, a truncated file. Named rather\nthan dropped: a model the operator can see and we cannot\nexplain is the worst of the three states.\n',
    )


class Scan(BaseModel):
    """
    State of the current or most recent walk of the configured
    roots. A singleton: there is exactly one scan, and inventing job
    ids for something that has exactly one is worse than not.

    """

    state: ScanState
    full: bool | None = Field(
        None, description='Whether this scan is ignoring the metadata cache.'
    )
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    roots: list[ScanRoot] | None = Field(
        None,
        description='Per-root outcome. A root that could not be read is reported\nhere and does not abort the scan: one unplugged drive must\nnot cost the operator every other model they own.\n',
    )
    currentPath: str | None = Field(
        None,
        description='What is being read right now. Present while `scanning`, and\nthe difference between a scan that is working and one that\nis wedged on a network share.\n',
    )
    filesScanned: int | None = Field(
        None, description='Files examined so far, across all roots.', ge=0
    )
    modelsFound: int | None = Field(
        None, description='Models in the library as of this scan.', ge=0
    )
    added: int | None = Field(
        None, description='Models this scan saw for the first time.', ge=0
    )
    updated: int | None = Field(
        None,
        description='Models whose metadata was re-read because the file changed.',
        ge=0,
    )
    missing: int | None = Field(
        None,
        description='Previously-known models this scan did not find. They keep\ntheir entries and their profiles; see `ModelStatus`.\n',
        ge=0,
    )
    skipped: list[SkippedPath] | None = Field(
        None,
        description='Paths deliberately not treated as models, each with a\nreason. **The important half of the response.** Every\nnot-a-model case is here — the projector beside a model, the\nsecond shard of a split file, an older revision in a\nHuggingFace cache — and the reason someone can find out why\ntheir model is not showing up. A scanner that silently drops\nwhat it did not understand is indistinguishable from a\nbroken one.\n',
    )
    error: str | None = Field(None, description='Populated when `state` is `failed`.')


class CatalogueSearchPage(BaseModel):
    results: list[CatalogueSearchResult]
    nextCursor: str | None = Field(
        None,
        description="Pass back as `cursor` for the next page. Absent on the last\npage. Opaque — it is upstream's own continuation token and\ncarries no page arithmetic.\n",
    )
    cachedAt: AwareDatetime | None = Field(
        None,
        description='When this answer was fetched upstream. Present because\nresults are cached for a short window to stay inside the\n500-request/300-second API budget, and a client showing\npopularity numbers should know they are minutes old.\n',
    )


class CatalogueCandidate(BaseModel):
    """
    One downloadable, launchable choice. **Shards are already
    summed here** — scoring the file named on the launch line
    understates a split candidate by the size of every other shard
    (verified: 46.55 GiB for shard 1 of a model that is 50.90 GiB).

    """

    label: str = Field(
        ...,
        description='What to show in the list: the quant tier for GGUF\n(`Q4_K_M`, `UD-IQ3_XXS`), or the variant directory for a\nsafetensors repo.\n',
    )
    format: ModelFormat
    files: list[CatalogueFile] = Field(
        ...,
        description='Every file this candidate needs, in the order a download\nshould fetch them. For a split GGUF, all shards. For\nsafetensors, the weights **and** the sidecars — `config.json`\nand the tokenizer files are not optional. Pass these\nstraight to `DownloadSpec.files`.\n',
    )
    sizeBytes: int = Field(
        ...,
        description='Sum over `files`. The number the fit verdict is computed from.',
        ge=0,
    )
    quantization: str | None = Field(
        None,
        description='Quant tier, e.g. `Q4_K_M`. GGUF only — a safetensors model\nis sized, not tiered.\n',
    )
    quantSource: QuantSource | None = Field(
        None,
        description='**Where the tier came from, and this field is load-bearing.**\n`filename` at listing time, because the hub exposes no\nper-file quant and the name is all there is — the very thing\na local scan refuses to trust. `metadata` after a preflight\nhas read `general.file_type` over HTTP Range.\n\nFit is computed from `sizeBytes`, which is authoritative\neither way, so a mislabelled file changes what is displayed\nand never what is promised.\n',
    )
    bitsPerWeight: float | None = Field(
        None,
        description='`sizeBytes × 8 / parameters`. The one quality-adjacent\nnumber here that is arithmetic rather than judgement, and\nthe only thing that makes three upstream naming schemes\ncomparable: on one verified repo it ordered all 25\ncandidates monotonically from 1.81 to exactly 16.00 for\nBF16 — that last value being the check that the parameter\ncount is real.\n\nAbsent when upstream states no parameter count.\n',
    )
    dtype: str | None = Field(
        None, description='Dominant tensor dtype, for safetensors candidates.'
    )
    fit: Fit | None = None
    alreadyOwned: AlreadyOwned | None = None
    gated: bool | None = Field(
        None,
        description="Convenience copy of the repo's gate, on the row the operator\nis about to click.\n",
    )


class CataloguePreflight(BaseModel):
    """
    What one remote file says about itself, read over HTTP Range
    without downloading it. See `preflightCatalogueFile` for the
    cost, which is the point of the endpoint.

    """

    repo: str
    resolvedCommit: str | None = None
    file: str
    format: ModelFormat
    bytesRead: int = Field(
        ...,
        description='How much of the remote file this cost. Reported so the\nnumber is visible rather than assumed: ~11 MB for a\nlarge-vocab GGUF, ~11 KB for a safetensors header. The GGUF\nfigure is mostly tokenizer — the metadata worth having sits\non the far side of the vocabulary, which is why the read is\nnot smaller.\n',
        ge=0,
    )
    quantization: str | None = Field(
        None,
        description='The tier, from `general.file_type`. Machine-read, not guessed.',
    )
    fileType: int | None = Field(
        None,
        description='Raw `general.file_type`. Reported alongside the label rather\nthan instead of it, for M2\'s reason: the quant families\nchurn and an unrecognised value must degrade to "here is the\nnumber", never to a plausible neighbour.\n',
    )
    agreesWithFilename: bool | None = Field(
        None,
        description='Whether the metadata tier and the filename tier match. When\nfalse both are reported and neither is silently preferred.\nThis is the check the whole endpoint exists to make\npossible.\n',
    )
    architecture: str | None = None
    blockCount: int | None = Field(
        None, description='Total layers the file declares.', ge=0
    )
    attentionLayers: int | None = Field(
        None,
        description='How many of those layers actually hold a KV cache. **Not\nthe same number** on a hybrid model: one current release\ndeclares 65 blocks with a full-attention interval of 4, so\n16 layers carry KV and the naive arithmetic overestimates\nthe cache by 4.1× at every context length. This field is\nwhat stops guidance from being confidently wrong about an\nentire class of modern models.\n',
        ge=0,
    )
    contextLength: int | None = Field(None, ge=0)
    parameters: int | None = Field(
        None,
        description='Exact count, for safetensors, from the summed tensor shapes\nin the header. Absent for GGUF, which does not carry one —\nthe same asymmetry the local scan meets, reproduced over the\nnetwork at wildly different cost.\n',
        ge=0,
    )
    dtype: str | None = None
    vocabSize: int | None = Field(None, ge=0)
    capabilities: ModelCapabilities | None = None
    recommendedSampling: RecommendedSampling | None = None
    fit: Fit | None = None
    shardCount: int | None = Field(
        None,
        description="From the file's own `split.count`, when it is a shard.\nProbing the **first** shard is enough — verified: shard 1 of\na split model carries the complete KV block.\n",
        ge=1,
    )


class Download(BaseModel):
    """
    One transfer job over N files. Records persist after they finish;
    `DELETE` forgets one.

    """

    id: str
    state: DownloadState
    repo: str
    revision: str | None = None
    resolvedCommit: str | None = Field(
        None,
        description='The commit this download is pinned to. A resume that finds\nupstream serving a different digest for the same path\nreports it here rather than appending new bytes to old ones.\n',
    )
    root: str | None = None
    destinationDirectory: str | None = Field(
        None,
        description='Absolute directory the files will land in, resolved **before\nthe first byte moves** so the operator can see where their\nmodel is going while there is still time to change it.\n',
    )
    files: list[DownloadFile]
    bytesTotal: int | None = Field(None, ge=0)
    bytesDownloaded: int | None = Field(None, ge=0)
    bytesPerSecond: float | None = Field(
        None, description='Recent rate, not an average over the whole job.', ge=0.0
    )
    etaSeconds: int | None = Field(None, ge=0)
    attempts: int | None = Field(
        None,
        description='How many times the transfer has been (re)started, including\nautomatic retries. Visible because a 40 GB fetch over a\ndomestic link will meet transient failures, and the\ndifference between a flaky connection and a dead one is\nthis number moving.\n',
        ge=0,
    )
    modelId: str | None = Field(
        None,
        description='The library entry this download became, filled in after the\npost-completion scan of the destination directory. This is\nwhat closes discovery → download → library → profile →\nlaunch without the UI polling for a model to appear.\n',
    )
    startedAt: AwareDatetime | None = None
    finishedAt: AwareDatetime | None = None
    error: str | None = None
    errorCode: str | None = Field(
        None,
        description='Upstream\'s own error code when it gave one — `GatedRepo` is\nthe one that will actually happen, and it means "accept the\nlicence on the model page" rather than anything the operator\ncan fix here. Carried through so the UI can say that instead\nof surfacing a bare 401.\n',
    )
    restartedFromZero: bool | None = Field(
        None,
        description='True when a resume found the remote file had changed and\ndiscarded the partial. Surfaced rather than silent: the\noperator is about to re-spend bandwidth they already spent,\nand the reason is that upstream requantized under the same\nfilename.\n',
    )
    message: str | None = Field(
        None, description='What the current phase is doing, for the progress dialog.'
    )


class LibraryModelList(BaseModel):
    models: list[LibraryModel]
    lastScanAt: AwareDatetime | None = Field(
        None,
        description='When the walk that produced this list finished. Omitted\nbefore the first scan. Present here as well as on `Scan` so\na browser rendering the list can say how stale it is\nwithout a second call.\n',
    )


class CatalogueModel(BaseModel):
    """
    One upstream repo, resolved: what it is, what can be downloaded
    from it, and which of those this host can run.

    """

    repo: str
    owner: str | None = None
    name: str | None = None
    revision: str = Field(
        ..., description='The revision that was asked for, e.g. `main`.'
    )
    resolvedCommit: str | None = Field(
        None,
        description='The commit `revision` resolved to, from upstream\'s\n`X-Repo-Commit`. Reported because `main` moves — repos are\nrequantized and re-uploaded under the same filenames — and\na download pins this so a later resume can tell "the\ntransfer broke" from "the file I was fetching is gone".\n',
    )
    gated: GateKind | None = None
    private: bool | None = None
    downloads: int | None = Field(None, ge=0)
    likes: int | None = Field(None, ge=0)
    trendingScore: float | None = None
    license: str | None = None
    tags: list[str] | None = None
    pipelineTag: str | None = None
    libraryName: str | None = None
    createdAt: AwareDatetime | None = None
    lastModified: AwareDatetime | None = None
    formats: list[ModelFormat] | None = Field(
        None, description='Formats actually present in the file list.'
    )
    parameters: int | None = Field(
        None,
        description="Parameter count, when upstream states one. For a GGUF repo\nit comes from the hub's own repo-level metadata and is\nexact — which is what makes `bitsPerWeight` computable with\nno extra request, and is the inverse of the local case where\na GGUF gives no parameter count at all.\n",
        ge=0,
    )
    architecture: str | None = None
    contextLength: int | None = Field(
        None,
        description='Context the model was trained for, per upstream. Not what\nthis host can serve — that is what `candidates[].fit`\nanswers, at a context the caller chose.\n',
        ge=0,
    )
    chatTemplate: bool | None = Field(
        None, description='Whether upstream reports an embedded chat template.'
    )
    candidates: list[CatalogueCandidate] = Field(
        ...,
        description='The launchable choices, one per quant or per format variant,\nwith shards already summed. **This is the list the operator\npicks from**, and it is materially shorter than the file\nlist: one verified repo held 30 `.gguf` files and 25\ncandidates.\n',
    )
    projectors: list[CatalogueFile] | None = Field(
        None,
        description="Vision projectors offered by this repo, as their own list\nbecause a multimodal repo ships more than one precision of\nthem and the operator picks — and because a projector is\nnever a candidate on its own. Add the chosen one to the\ndownload's `files`.\n",
    )
    otherFiles: list[CatalogueFile] | None = Field(
        None,
        description='Files in the repo that are neither candidates nor\nprojectors: the imatrix calibration file, an MTP or draft\nmodel, documentation. Reported rather than hidden, for the\nsame reason the scan reports `skipped` — a listing that\nsilently drops files it did not understand is\nindistinguishable from one that is broken.\n',
    )
    totalSizeBytes: int | None = Field(
        None,
        description='Every file in the repo summed. Rarely what anyone wants to download.',
        ge=0,
    )
    recommended: CatalogueRecommendation | None = None
    warnings: list[str] | None = Field(
        None,
        description='Things to say before a download starts: the repo is gated,\nnothing here fits, the only thing that fits is a very low\nquant, upstream metadata was unreadable so the fit is a\nsize estimate.\n',
    )


class DownloadList(BaseModel):
    downloads: list[Download]
